name: Slack

on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: C04QKFBN45C
        SLACK_TEXT: "An alert was generated on webdriveriotest repo"
